package com.qentelli.automation.utilities;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class BBTestDataObject extends  AbstractApplicationsTestdataResourceBundle {
    protected static Logger logger = LogManager.getLogger(TBBTestDataObject.class);
    private final static String NAME = "BB";

    public  String ODPTitleCanadaEnglish;
    public  String ODPTitleCanadaFrench;
    public  String ODPTitleUnitedKingdomEnglish;
    public  String homePageODPTitle;
    public  String cardHolderFirstName;
    public  String cardHolderLastName;
    public  String cardNumber;
    public  String emailFromExistingAccount;
    public  String emailFromExistingNonClubAccount;
    public  String emailFromExistingAccountWith2mindsetUPF;
    public  String emailFromExistingAccountPCClubUser;
    public  String emailFromExistingAccountStandardFlow;
    public  String expirationDate;
    public  String orderNumber;
    public  String password;
    public  String popUpMessage;
    public  String securityCode;
    public  String homePageTitle;
    public  String zipCode;
    public  String zipCodeWithTax;
    public  String threeMonthsPlanSubTitle;
    public  String threeMonthsPlanCost;
    public  String threeMonthsPlanMembershipMsg;
    public  String popUPModelSignInText;
    public  String popUPModelUseDifferentEmailText;
    public  String existedCoachUserEmail;
    public  String existingClubUserEmailWithBODINT;
    public  String apartmentAddress;
    public  String cityAddress;
    public String accountPageHeader;
    public String accountPageSubHeader;
    public String skuTitle;
    public String subTotal;
    public String shippingAndHandlingAmount;
    public String estimateTax;
    public String estimateTotal;
    public String termsAndConditions;
    public String creditCardDisclaimer;
    public String textMembershipInfoDisclaimer;
    public String textBODiInfoDisclaimer;
    public String refferalCoachID;
    public  String streetAddress;
    public  String errorMsgUnderCardHolderFirstNameField;
    public  String errorMsgUnderCardHolderLastNameField;
    public  String errorMsgUnderCreditCardCVVNumber;
    public  String errorMsgUnderCreditCardNumber;
    public  String textPrePopulatedCCDetails;
    public  String textPriceInOrderSummary;
    public  String textDisclaimer1;
    public  String textDisclaimer2;
    public  String textDisclaimer3;
    public  String textDisclaimer4;
    public  String textDisclaimer5;
    public  String wrongPassword;
    public  String wrongPasswordErrorMsg;
    public  String faqUrl;
    public  String errorMsgUnderUserFName;
    public  String errorMsgUnderUserLName;
    public  String taxValue;
    public  String editEmailPage;

    public BBTestDataObject() {
        super(NAME);
        accountPageHeader = getResString("ACCOUNTPAGEHEADER");
        accountPageSubHeader = getResString("ACCOUNTPAGESUBHEADER");
        cardHolderFirstName = getResString("CARDHOLDERFIRSTNAME");
        cardHolderLastName = getResString("CARDHOLDERLASTNAME");
        cardNumber = getResString("CARDNUMBER");
        emailFromExistingAccount = getResString("EMAILFROMEXISTINGACCOUNT");
        emailFromExistingNonClubAccount = getResString("EMAILFROMEXISTINGNONCLUBACCOUNT");
        emailFromExistingAccountWith2mindsetUPF = getResString("EMAILFROMEXISTINGACCOUNTWITH2BMINDSETUPF");
        emailFromExistingAccountPCClubUser = getResString("EMAILFROMEXISTINGACCOUNTPCCLUBUSER");
        existedCoachUserEmail = getResString("EXISTEDCOACHUSEREMAIL");
        existingClubUserEmailWithBODINT = getResString("EXISTINGCLUBUSEREMAILWITHBODINT");
        emailFromExistingAccountStandardFlow = getResString("EMAILFROMEXISTINGACCOUNTSTANDARDFLOW");
        expirationDate = getResString("EXPIRATIONDATE");
        orderNumber = getResString("ORDERNUMBER");
        password = getResString("PASSWORD");
        popUpMessage = getResString("POPUPMESSAGE");
        securityCode = getResString("SECURITYCODE");
        ODPTitleCanadaEnglish = getResString("ODPTITLECANADAENGLISH");
        ODPTitleCanadaFrench = getResString("ODPTITLECANADAFRENCH");
        homePageODPTitle = getResString("HOMEPAGEODPTITLE");
        ODPTitleUnitedKingdomEnglish = getResString("ODPTITLEUNITEDKINGDOMENGLISH");
        homePageTitle = getResString("HOMEPAGETITLE");
        zipCode = getResString("ZIPCODE");
        zipCodeWithTax = getResString("ZIPCODEWITHTAX");
        refferalCoachID = getResString("REFFERALCOACHID");
        threeMonthsPlanCost = getResString("THREEMONTHSPLANCOST");
        threeMonthsPlanSubTitle = getResString("THREEMONTHSPLANSUBTITLE");
        threeMonthsPlanMembershipMsg = getResString("THREEMONTHSPLANMEMBERSHIPMSG");
        popUPModelSignInText = getResString("POPUPMODELSIGNINTEXT");
        popUPModelUseDifferentEmailText = getResString("POPMODELUSEDIFFERENTEMAILTEXT");
        streetAddress = getResString("STREETADDRESS");
        cityAddress = getResString("CITYADDRESS");
        accountPageHeader = getResString("ACCOUNTPAGEHEADER");
        accountPageSubHeader = getResString("ACCOUNTPAGESUBHEADER");
        skuTitle = getResString("SKUTITLE");
        subTotal = getResString("SUBTOTAL");
        shippingAndHandlingAmount = getResString("SHIPPINGANDHANDLINGAMOUNT");
        estimateTax = getResString("ESTIMATETAX");
        estimateTotal = getResString("ESTIMATETOTAL");
        termsAndConditions = getResString("TERMSANDCONDITIONS");
        creditCardDisclaimer = getResString("CREDITCARDDISCLIMERS");
        textMembershipInfoDisclaimer = getResString("TEXTMEMBERSHIPINFODISCLAIMER");
        textBODiInfoDisclaimer = getResString("TEXTBODIINFODISCLAIMER");
        apartmentAddress = getResString("APARTMENTADDRESS");
        errorMsgUnderCardHolderFirstNameField = getResString("ERRORMSGUNDERCARDHOLDERFIRSTNAMEFIELD");
        errorMsgUnderCardHolderLastNameField = getResString("ERRORMSGUNDERCARDHOLDERLASTNAMEFIELD");
        errorMsgUnderCreditCardCVVNumber = getResString("ERRORMSGUNDERCREDITCARDCVVNUMBER");
        errorMsgUnderCreditCardNumber = getResString("ERRORMSGUNDERCREDITCARDNUMBER");
        textPrePopulatedCCDetails = getResString("TEXTPREPOPULATEDCCDETAILS");
        textPriceInOrderSummary = getResString("TEXTMYXFLOWPRICEINORDERSUMMARY");
        textDisclaimer1 = getResString("TEXTDISCLAIMER1");
        textDisclaimer2 = getResString("TEXTDISCLAIMER2");
        textDisclaimer3 = getResString("TEXTDISCLAIMER3");
        textDisclaimer4 = getResString("TEXTDISCLAIMER4");
        textDisclaimer5 = getResString("TEXTDISCLAIMER5");
        wrongPassword = getResString("WRONGPASSWORD");
        wrongPasswordErrorMsg = getResString("WRONGPASSWORDERRORMSG");
        faqUrl = getResString("FAQURL");
        errorMsgUnderUserFName = getResString("ERRORMSGUNDERUSERFNAME");
        errorMsgUnderUserLName = getResString("ERRORMSGUNDERUSERLNAME");
        taxValue = getResString("TAXVALUE");
        editEmailPage = getResString("EDITEMAILPAGE");
    }

    public String getValue(String key){
        return getResString(key);
    }
}
