package com.qentelli.automation.utilities;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class SHACTestDataObject extends  AbstractApplicationsTestdataResourceBundle {

    protected static Logger logger = LogManager.getLogger(TBBTestDataObject.class);
    private final static String NAME = "SHAC";

    public String SSETBBloginUserPassword;
    public String beachbarPCPrice;
    public String beachbarProductTitle;
    public String bodi30DayMembershipDisclaimerText;
    public String busnessStarterKitTitle;
    public String emailSubCompleteYourPurchase;
    public String labelTextBODi30DayMembership;
    public String loginPassword;
    public String notMoreThanOneBODIRestrictionMessage;
    public String pcPriceLabel;
    public String pricetestStep;
    public String priceChinUpBar;
    public String quantityOptiontestStep;
    public String quantityOptionChinUpBar;
    public String quantityValuetestStep;
    public String quantityValueChinUpBar;
    public String quantityValueResistanceLoops;
    public String resistanceLoopsOptions;
    public String restrictedMsgHeader;
    public String selectBODMembershipOption;
    public String selectBODPlusBODiMembership;
    public String selectBODPlusBODi12MonthsOption;
    public String selectBod12MonthsAndBodi30daysOption;
    public String selectBod12MonthsOption;
    public String selectBod6MonthsOption;
    public String selectBod3MonthsOption;
    public String selfSponsoredPC;
    public String shacChallengePackRestrictedMsg;
    public String shacUserSet2;
    public String shacUserSet3;
    public String shacUserSet4;
    public String shacUserSetpreferredCustomerDifferentThanSponsorCoach;
    public String shacUserSetpreferredCustomerSponsorCoach;
    public String shacUserSet2BMindset;
    public String tbbLoginPassword;
    public String text2BMindsetKitPrice;
    public String textAnnualBODShakeologyCP;
    public String textBODCoach;
    public String textBODCustomer;
    public String textBSK;
    public String textBSKPrice;
    public String textCookiesAndCreamyShakeology;
    public String textCurrencyLabel;
    public String textEnrollWithoutPurchase;
    public String textFree;
    public String textFreeMembership;
    public String textMorningMeltdownCPPack;
    public String textNotACoachAccessError;
    public String textRegularCoach;
    public String textRegularCustomer;
    public String textResistanceLoopsPrice;
    public String titletestStep;
    public String titleChinUpBar;
    public String titleResistanceLoops;
    public String bodCustomerWithPayment;
    public String breakawayAccessoryBundle;
    public String bodAnnualMembership;
    public String bodiMonthlyMembership;
    public String coachBSFDisclaimerText;
    public String bodAnnualMembershipDisclaimerText;
    public String text2BMindSetRestrictionMessage;
    public String text2BMindsetAlreadyExistMessage;
    public String textPerformanceStackDisclaimer;
    public String textChocolateShakeology;
    public String textSelfSponsoredNonBodPcMessage;
    public String textSelfSponsoredBodPcMessage;
    public String textSelfSponsoredBodCoachMessage;
    public String textNonSelfSponsoredNonBodPcMessage;
    public String textNonSelfSponsoredBodPcMessage;
    public String textCopyShareableLink;
    public String select12InchResistanceLoop;
    public String nonPersonallySponsoredCoachEmail;
    public String personallySponsoredCoachEmail;
    public String nonPersonalSponsoredBodBodiEmail;
    public String nonPersonalSponsoredPcBodiEmail;
    public String nonPersonalSponsoredCoachBodiEmail;
    public String personalSponsoredBodBodiEmail;
    public String personalSponsoredPcBodiEmail;
    public String personalSponsoredCoachBodiEmail;
    public String nonPersonalSponsoredBodBodiUserTypeInfo;
    public String nonPersonalSponsoredPcBodiUserTypeInfo;
    public String nonPersonalSponsoredCoachBodiUserTypeInfo;
    public String personalSponsoredBodBodiUserTypeInfo;
    public String personalSponsoredPcBodiUserTypeInfo;
    public String personalSponsoredCoachBodiUserTypeInfo;
    public String defaultPassword;
    public String textSelfSponsoredFreeCustomerMessage;
    public String textMissingEmailErrorMessage;
    public String textInvalidEmailErrorMessage;
    public String twoBMindsetKitTitle;
    public String bskPrice;
    public String currency;
    public String textBODRestrictionMessage;

    public SHACTestDataObject() {
        super(NAME);
        SSETBBloginUserPassword = getResString("SSE_TBB_login_userPassword");
        beachbarPCPrice = getResString("BEACHBAR_PC_PRICE");
        beachbarProductTitle = getResString("BEACHBAR_PRODUCT_TITLE");
        bodi30DayMembershipDisclaimerText = getResString("BODI30DAYMEMBERSHIPDISCLAIMERTEXT");
        busnessStarterKitTitle = getResString("BUSINESS_STARTER_KIT_TITLE");
        emailSubCompleteYourPurchase = getResString("EMAILSUBJECTCOMPLETEYOURTBBPURCHASE");
        labelTextBODi30DayMembership = getResString("LABELTEXTBODI30DAYMEMBERSHIP");
        loginPassword = getResString("loginPassword");
        notMoreThanOneBODIRestrictionMessage = getResString("NOTMORETHANONEBODIRESTRICTIONMESSAGE");
        pcPriceLabel = getResString("PREFERRED_CUSTOMER_LABEL");
        pricetestStep = getResString("PRICEtestSTEP");
        priceChinUpBar = getResString("PRICECHINUPBAR");
        quantityOptiontestStep = getResString("QUANTITYOPTIONtestSTEP");
        quantityOptionChinUpBar = getResString("QUANTITYOPTIONCHINUPBAR");
        quantityValuetestStep = getResString("QUANTITYVALUEtestSTEP");
        quantityValueChinUpBar = getResString("QUANTITYVALUECHINUPBAR");
        quantityValueResistanceLoops = getResString("QUANTITYVALUERESISTANCELOOPS");
        resistanceLoopsOptions = getResString("RESISTANCELOOPOPTIONS");
        restrictedMsgHeader =getResString("RESTRICTEDMSGHEADER");
        selectBODPlusBODiMembership = getResString("SELECTBODPLUSBODIMEMBERSHIP");
        selectBODMembershipOption = getResString("SELECTBODMEMBERSHIPOPTION");
        selectBODPlusBODi12MonthsOption = getResString("SELECTBODPLUSBODI12MONTHSOPTION");
        selectBod12MonthsAndBodi30daysOption = getResString("SELECTBOD12MONTHSANDBODI30DAYSOPTION");
        selectBod12MonthsOption = getResString("SELECTBOD12MONTHSOPTION");
        selectBod6MonthsOption = getResString("SELECTBOD6MONTHSOPTION");
        selectBod3MonthsOption = getResString("SELECTBOD3MONTHSOPTION");
        selfSponsoredPC =getResString("SelfSponsoredPC");
        shacChallengePackRestrictedMsg = getResString("SHACCHALLENGEPACKRESTRICTEDMSG");
        shacUserSet2 = getResString("Shac_User_Set_2");
        shacUserSet3 = getResString("Shac_User_Set_3");
        shacUserSet4 = getResString("Shac_User_Set_4");
        shacUserSetpreferredCustomerDifferentThanSponsorCoach = getResString("Shac_User_Set_preferredCustomerDifferentThanSponsorCoach");
        shacUserSetpreferredCustomerSponsorCoach = getResString("Shac_User_Set_preferredCustomerSponsorCoach");
        shacUserSet2BMindset = getResString("SHACUSERSET2BMINDSET");
        tbbLoginPassword = getResString("TBBLoginPassword");
        text2BMindsetKitPrice = getResString("TEXT2BMINDSETKITPRICE");
        textAnnualBODShakeologyCP = getResString("TEXTANNUALBODSHAKEOLOGYCP");
        textBODCoach = getResString("TEXTBODCOACH");
        textBODCustomer = getResString("TEXTBODCUSTOMER");
        textBSK = getResString("TEXTBSK");
        textBSKPrice = getResString("TEXTBSKPRICE");
        textCookiesAndCreamyShakeology = getResString("TEXTCOOKIESANDCREAMYSHAKEOLOGY");
        textCurrencyLabel = getResString("TEXTCURRENCYLABEL");
        textEnrollWithoutPurchase = getResString("TEXTENROLLWITHOUTPURCHASE");
        textFree = getResString("TEXTFREE");
        textFreeMembership = getResString("TEXTFREEMEMEMBERSHIP");
        textMorningMeltdownCPPack = getResString("TEXTMORNINGMELTDOWNCPPACK");
        textNotACoachAccessError = getResString("TEXTNOTACOACHACCESSERROR");
        textRegularCoach = getResString("TEXTREGULARCOACH");
        textRegularCustomer = getResString("TEXTREGULARCUSTOMER");
        textResistanceLoopsPrice = getResString("TEXTRESISTANCELOOPPRICE");
        titletestStep = getResString("TITLEtestSTEP");
        titleChinUpBar = getResString("TITLECHINUPBAR");
        titleResistanceLoops = getResString("TITLERESISTANCELOOPS");
        quantityValueResistanceLoops = getResString("QUANTITYVALUERESISTANCELOOPS");
        bodCustomerWithPayment = getResString("BODCUSTOMERWITHPAYMENT");
        breakawayAccessoryBundle = getResString("BREAKAWAYACCESSORYBUNDLE");
        bodAnnualMembership = getResString("BODANNUALMEMBERSHIP");
        bodiMonthlyMembership = getResString("BODIMONTHLYMEMBERSHIP");
        coachBSFDisclaimerText = getResString("COACHBSFDISCLAIMER");
        bodAnnualMembershipDisclaimerText = getResString("BODANNUALMEMBERSHIPDISCLAIMER");
        text2BMindSetRestrictionMessage = getResString("TEXT2BMINDSETRESTRICTIONMESSAFE");
        text2BMindsetAlreadyExistMessage = getResString("TEXT2BMINDSETALREADYEXISTMESSAGE");
        textPerformanceStackDisclaimer = getResString("TEXTPERFORMANCESTACKDISCLAIMER");
        textChocolateShakeology = getResString("TEXTCHOCOLATESHAKEOLOGY");
        textSelfSponsoredNonBodPcMessage = getResString("TEXTSELFSPONSOREDNONBODPCMESSAGE");
        textSelfSponsoredBodPcMessage = getResString("TEXTSELFSPONSOREDBODPCMESSAGE");
        textSelfSponsoredBodCoachMessage = getResString("TEXTSELFSPONSOREDBODCOACHMESSAGE");
        textNonSelfSponsoredNonBodPcMessage = getResString("TEXTNONSELFSPONSOREDNONBODPCMESSAGE");
        textNonSelfSponsoredBodPcMessage = getResString("TEXTNONSELFSPONSOREDBODPCMESSAGE");
        textCopyShareableLink = getResString("TEXTCOPYSHAREABLELINK");
        select12InchResistanceLoop = getResString("SELECT12INCHRESISTANCELOOP");
        nonPersonallySponsoredCoachEmail =getResString("NONPERSONALLYSPONSOREDCOACH");
        personallySponsoredCoachEmail =getResString("PERSONALLYSPONSOREDCOACH");
        nonPersonalSponsoredBodBodiEmail = getResString("NONPERSONALSPONSOREDBODBODI");
        nonPersonalSponsoredPcBodiEmail = getResString("NONPERSONALSPONSOREDPCBODI");
        nonPersonalSponsoredCoachBodiEmail = getResString("NONPERSONALSPONSOREDCOACHBODI");
        personalSponsoredBodBodiEmail = getResString("PERSONALSPONSOREDBODBODI");
        personalSponsoredPcBodiEmail = getResString("PERSONALSPONSOREDPCBODI");
        personalSponsoredCoachBodiEmail = getResString("PERSONALSPONSOREDCOACHBODI");
        defaultPassword = getResString("DEFAULTPASSWORD");
        personalSponsoredBodBodiUserTypeInfo = getResString("PERSONALSPONSOREDBODBODIUSERTYPEINFO");
        personalSponsoredPcBodiUserTypeInfo = getResString("PERSONALSPONSOREDPCBODIUSERTYPEINFO");
        personalSponsoredCoachBodiUserTypeInfo = getResString("PERSONALSPONSOREDCOACHBODIUSERTYPEINFO");
        nonPersonalSponsoredBodBodiUserTypeInfo = getResString("NONPERSONALSPONSOREDBODBODIUSERTYPEINFO");
        nonPersonalSponsoredPcBodiUserTypeInfo = getResString("NONPERSONALSPONSOREDPCBODIUSERTYPEINFO");
        nonPersonalSponsoredCoachBodiUserTypeInfo = getResString("NONPERSONALSPONSOREDCOACHBODIUSERTYPEINFO");
        textSelfSponsoredFreeCustomerMessage=getResString("TEXTSELFSPONSOREDFREECUSTOMERMESSAGE");
        textMissingEmailErrorMessage=getResString("TEXTMISSINGEMAIL");
        textInvalidEmailErrorMessage=getResString("TEXTINVALIDEMAIL");
        twoBMindsetKitTitle=getResString("TWOBMINDSETKITTITLE");
        bskPrice=getResString("BSKPRICE");
        currency=getResString("CURRENCY");
        textBODRestrictionMessage=getResString("TEXTBODRESTRICTIONMESSAGE");
    }

    public String getValue(String key){
        return getResString(key);
    }
}
